title: AI Inside Out
description: The best AI news and resources curated by the best experts
repository: insideout/ai
baseurl: ""
url: https://ai.insideout.app

collections:
  - topics
  - learning
  - demos
  - apis
  - scholars
  - influencers

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /api/:categories/:year/:month/:day/:title/index.json
      locale: en-us
      isBreakingNews: false
      isTopStory: false
      deleted: false
  - scope:
      path: ""
      type: learning
    values:
      layout: learning
      locale: en-us
      deleted: false
  - scope:
      path: ""
      type: demos
    values:
      layout: demo
      locale: en-us
      deleted: false
  - scope:
      path: ""
      type: apis
    values:
      layout: api
      locale: en-us
      deleted: false
  - scope:
      path: ""
      type: scholars
    values:
      layout: scholar
      locale: en-us
      deleted: false
  - scope:
      path: ""
      type: influencers
    values:
      layout: influencer
      locale: en-us
      deleted: false
  - scope:
      path: "api/*/*"
    values:
      permalink: /:path/index.json
